version = 0.1

[default]

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = false
log_retention = 7
parameter_overrides = [
  "VPCId=vpc-01f93da052cf2c0fa",
  "SubnetId1=subnet-0ca1afd1bb4f31dae",
  "SubnetId2=subnet-058dda5a839d50d38",
  "RDSInstanceSecurityGroup=sg-0bb9177dbdd7fabae",
  "paramCountry=cl",
  "paramEnvironment=prod",
  "paramDomainName=activity.cl.pragmadev.com.br",
  "paramCertificateId=d44dd647-97f8-45c1-ba03-6e12cbf1341f",
  "paramHostedZoneId=Z052296833IA491A0PGKH",
]
profile = "pragma-cl-prod"
region = "us-west-1"
resolve_s3 = true
s3_prefix = "tm-pragmadev-cl-prod-activity-crowder"
stack_name = "cl-prod-activity-crowder"
tags = [
  "environment=prod",
  "project=Activity Crowder Data Ingestion",
  "country=cl",
  "managed-by=AWS SAM",
]

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
disable_rollback = false
log_retention = 7
parameter_overrides = [
  "VPCId=vpc-08757369d1c4deaf6",
  "SubnetId1=subnet-0d8f2e887d08effc2",
  "SubnetId2=subnet-0115ac9aeb27fc82e",
  "RDSInstanceSecurityGroup=sg-0a3e8409fbd8aaa08",
  "paramCountry=cl",
  "paramEnvironment=dev",
  "paramDomainName=activity-dev.cl.pragmadev.com.br",
  "paramCertificateId=08ffa506-3a1f-4426-8737-b3102e9b29cf",
  "paramHostedZoneId=Z052296833IA491A0PGKH",
]
profile = "pragma-cl-dev"
region = "us-west-2"
resolve_s3 = true
s3_prefix = "tm-pragmadev-cl-dev-activity-crowder"
stack_name = "cl-dev-activity-crowder"
tags = [
  "environment=dev",
  "project=Activity Crowder Data Ingestion",
  "country=cl",
  "managed-by=AWS SAM",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true