version = 0.1

[default]

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = false
log_retention = 7
parameter_overrides = [
  "VPCId=vpc-0bbe2254b61c218fc",
  "SubnetId1=subnet-0914d1ea934a7d808",
  "SubnetId2=subnet-0f5f4748a70412aba",
  "RDSInstanceSecurityGroup=sg-085e218124666ca35",
  "paramCountry=br",
  "paramEnvironment=prod",
  "paramDomainName=activity.br.pragmadev.com.br",
  "paramCertificateId=8752660b-c979-45b5-ad84-b00d8b3006fe",
  "paramHostedZoneId=Z0821820KEVZXM5H90NU",
]
profile = "pragma-bra-prod"
region = "us-west-1"
resolve_s3 = true
s3_prefix = "tm-pragmadev-br-prod-activity-crowder"
stack_name = "br-prod-activity-crowder"
tags = [
  "environment=prod",
  "project=Activity Crowder Data Ingestion",
  "country=br",
  "managed-by=AWS SAM",
]

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
disable_rollback = false
log_retention = 7
parameter_overrides = [
  "VPCId=vpc-0bbe2254b61c218fc",
  "SubnetId1=subnet-0914d1ea934a7d808",
  "SubnetId2=subnet-0f5f4748a70412aba",
  "RDSInstanceSecurityGroup=sg-085e218124666ca35",
  "paramCountry=br",
  "paramEnvironment=dev",
  "paramDomainName=activity-dev.br.pragmadev.com.br",
  "paramCertificateId=a2bfa6bc-3a10-494f-801f-69d520c0349f",
  "paramHostedZoneId=Z0821820KEVZXM5H90NU",
]
profile = "pragma-bra-dev"
region = "us-west-2"
resolve_s3 = true
s3_prefix = "tm-pragmadev-br-dev-activity-crowder"
stack_name = "br-dev-activity-crowder"
tags = [
  "environment=dev",
  "project=Activity Crowder Data Ingestion",
  "country=br",
  "managed-by=AWS SAM",
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
